const buildVersion=new URL(import.meta.url).searchParams.get('v')||'2.4.3-beta';
const {CATEGORIES,seed,validateTransaction,summarize}=await import('./domain.mjs?v='+encodeURIComponent(buildVersion));
const {RELEASE}=await import('./releases.mjs?v='+encodeURIComponent(buildVersion));
const $=s=>document.querySelector(s),money=c=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(c/100),esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
const KEY='catheu-demo-session-v1';let rows=seed(),view='inicio',category='',confirmAction=null,toastTimer;
try{const saved=JSON.parse(sessionStorage.getItem(KEY));if(Array.isArray(saved)&&saved.length<=100&&saved.every(r=>typeof r.id==='string'&&r.id.length<100&&Number.isSafeInteger(r.cents)&&r.cents>0&&r.cents<=100000000&&typeof r.description==='string'&&r.description.length<=80&&/^2026-(09|10)-\d{2}$/.test(r.date)&&['INCOME','EXPENSE'].includes(r.type)&&[...CATEGORIES,'Receitas'].includes(r.category)))rows=saved;}catch{}
function save(){try{sessionStorage.setItem(KEY,JSON.stringify(rows));}catch{}render();}
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,3500);}
function txMarkup(r,actions=false){return `<div class="tx"><div class="tx-icon ${r.type==='EXPENSE'?'out':''}" aria-hidden="true">${r.type==='INCOME'?'↙':'↗'}</div><div class="tx-info"><strong>${esc(r.description)}</strong><small>${r.date.split('-').reverse().join('/')} · ${esc(r.category)}</small></div><div class="tx-value"><strong class="${r.type==='INCOME'?'positive':'negative'}">${r.type==='INCOME'?'+':'−'} ${money(r.cents)}</strong>${actions?`<div class="tx-actions"><button data-edit="${esc(r.id)}" aria-label="Editar ${esc(r.description)}">Editar</button><button data-delete="${esc(r.id)}" aria-label="Excluir ${esc(r.description)}">Excluir</button></div>`:''}</div></div>`;}
function render(){const month=$('#month').value,s=summarize(rows,month),sorted=rows.filter(r=>r.date.startsWith(month)).sort((a,b)=>b.date.localeCompare(a.date));$('#income').textContent=money(s.income);$('#expense').textContent=money(s.expense);$('#net').textContent=money(s.net);$('#net').style.color=s.net<0?'var(--red)':'var(--accent)';$('#cashIncome').textContent=money(s.income);$('#cashExpense').textContent=money(s.expense);const max=Math.max(s.income,s.expense,1);$('#incomeBar').style.width=s.income/max*100+'%';$('#expenseBar').style.width=s.expense/max*100+'%';$('#categoryChart').innerHTML=s.categories.length?s.categories.map(c=>{const width=c.cents/s.expense*100;return `<button class="category-row" data-category="${esc(c.name)}" aria-pressed="${category===c.name}"><span class="category-heading"><span>${esc(c.name)}</span><strong>${money(c.cents)} <small>· ${Math.round(width)}%</small></strong></span><div class="track"><i class="spending-bar" style="width:${width}%;--gradient-size:${10000/width}%"></i></div></button>`;}).join(''):'<p class="empty">Nenhuma despesa neste período.</p>';$('#clearCategory').hidden=!category;$('#insightTitle').textContent=s.net<0?'Os gastos superaram as receitas.':s.expense===0?'Um mês sem despesas registradas.':'As receitas cobrem os gastos.';$('#insightText').textContent=s.net<0?`As despesas ficaram ${money(-s.net)} acima das receitas neste exemplo.`:s.income?`Você gastou ${Math.round(s.expense/s.income*100)}% do que entrou. ${s.categories[0]?s.categories[0].name+' é a maior categoria de despesas.':''}`:'Adicione uma receita fictícia para começar a comparar.';$('#recentList').innerHTML=sorted.slice(0,4).map(r=>txMarkup(r)).join('')||'<p class="empty">Nenhum lançamento no período.</p>';const query=$('#search').value.trim().toLocaleLowerCase('pt-BR'),type=$('#typeFilter').value,cat=$('#categoryFilter').value;const filtered=sorted.filter(r=>(!type||r.type===type)&&(!cat||r.category===cat)&&(!query||(r.description+' '+r.category).toLocaleLowerCase('pt-BR').includes(query)));$('#transactionList').innerHTML=filtered.map(r=>txMarkup(r,true)).join('')||'<p class="empty">Nenhum resultado. Experimente limpar os filtros.</p>';$('#rowCount').textContent=filtered.length+' lançamento'+(filtered.length===1?'':'s');}
function go(next){window.scrollTo(0,0);view=next;$('#homeView').hidden=view!=='inicio';$('#transactionsView').hidden=view!=='movimentacoes';$('#pageTitle').textContent=view==='inicio'?'Seu dinheiro, mais claro.':'Cada movimento, no seu lugar.';document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));history.replaceState(null,'','#'+view);render();}
const features={'Importação de extratos':'Importe extratos, revise duplicatas e identifique transferências entre suas contas.','Cartões e faturas':'Acompanhe compras, parcelas e faturas sem contar a mesma despesa duas vezes.','Planejamento e metas':'Organize metas, reservas, orçamentos e compromissos futuros.','Investimentos':'Explore simulações e referências de indicadores econômicos.','Contas a pagar e boletos':'Acompanhe vencimentos e registre a forma efetiva de cada pagamento.','Relatórios completos':'Compare períodos e explore gráficos com categorias, subcategorias e filtros detalhados.','Recursos completos':'Importação de extratos, cartões, planejamento, investimentos, contas a pagar e relatórios detalhados fazem parte da experiência completa.'};
function contact(feature){$('#contactTitle').textContent=feature==='CATHEU completo'?'Vamos conversar sobre o CATHEU?':feature;$('#contactDescription').textContent=features[feature]||'Conheça uma experiência completa para organizar e entender suas finanças.';$('#contactEmail').href='mailto:msbraga47@gmail.com?subject='+encodeURIComponent('Quero conhecer o CATHEU — '+feature);$('#contactDialog').showModal();}
function openForm(id){const form=$('#transactionForm');form.reset();$('#formError').textContent='';const r=rows.find(x=>x.id===id);$('#formTitle').textContent=r?'Editar movimentação':'Nova movimentação';form.elements.id.value=r?.id||'';form.elements.date.value=r?.date||$('#month').value+'-08';if(r){form.elements.type.value=r.type;form.elements.description.value=r.description;form.elements.amount.value=(r.cents/100).toFixed(2).replace('.',',');form.elements.category.value=r.category;}syncType();$('#transactionDialog').showModal();}
function syncType(){$('#formCategory').hidden=$('#transactionForm').elements.type.value==='INCOME';}
$('#categoryFilter').insertAdjacentHTML('beforeend',CATEGORIES.map(c=>`<option>${c}</option>`).join('')+'<option>Receitas</option>');$('#transactionForm').elements.category.innerHTML=CATEGORIES.map(c=>`<option>${c}</option>`).join('');
$('#newTransaction').onclick=()=>openForm();$('#transactionForm').elements.type.onchange=syncType;
$('#transactionForm').onsubmit=e=>{e.preventDefault();try{const data=Object.fromEntries(new FormData(e.currentTarget)),item=validateTransaction(data),id=data.id;if(!id&&rows.length>=100)throw Error('Esta demo permite até 100 exemplos. Exclua um ou restaure os dados.');if(id){const i=rows.findIndex(r=>r.id===id);if(i<0)throw Error('Exemplo não encontrado.');rows[i]={...item,id};}else rows.push({...item,id:crypto.randomUUID()});save();$('#transactionDialog').close();toast('Exemplo salvo. Os totais foram atualizados.');}catch(error){$('#formError').textContent=error.message;}};
document.addEventListener('click',e=>{const target=e.target.closest('button');if(!target)return;if(target.hasAttribute('data-close')){target.closest('dialog').close();return;}if(target.dataset.view){go(target.dataset.view);return;}if(target.dataset.feature){contact(target.dataset.feature);return;}if(target.dataset.category){category=target.dataset.category;$('#categoryFilter').value=category;$('#typeFilter').value='EXPENSE';$('#search').value='';go('movimentacoes');return;}if(target.dataset.edit){openForm(target.dataset.edit);return;}if(target.dataset.delete){const r=rows.find(x=>x.id===target.dataset.delete);if(!r)return;$('#confirmTitle').textContent='Excluir este exemplo?';$('#confirmText').textContent=r.description+' · '+money(r.cents);$('#confirmAction').textContent='Excluir exemplo';confirmAction=()=>{rows=rows.filter(x=>x.id!==r.id);save();toast('Exemplo excluído.');};$('#confirmDialog').showModal();}});
$('#confirmAction').onclick=()=>{confirmAction?.();confirmAction=null;$('#confirmDialog').close();};$('#resetDemo').onclick=()=>{$('#confirmTitle').textContent='Restaurar a demonstração?';$('#confirmText').textContent='Os exemplos que você alterou nesta aba serão substituídos pelos valores iniciais.';$('#confirmAction').textContent='Restaurar exemplos';confirmAction=()=>{rows=seed();category='';$('#categoryFilter').value='';$('#typeFilter').value='';$('#search').value='';save();toast('Demonstração restaurada.');};$('#confirmDialog').showModal();};
$('#clearCategory').onclick=()=>{category='';$('#categoryFilter').value='';render();};$('#month').onchange=()=>{category='';$('#categoryFilter').value='';render();};['search','typeFilter','categoryFilter'].forEach(id=>$('#'+id).addEventListener('input',()=>{category=$('#categoryFilter').value;render();}));
$('#copyEmail').onclick=async()=>{try{await navigator.clipboard.writeText('msbraga47@gmail.com');toast('E-mail copiado.');}catch{toast('Copie o endereço exibido acima: msbraga47@gmail.com');}};
document.querySelector('.brand').addEventListener('click',e=>{e.preventDefault();go('inicio');});
$('#versionLabel').textContent=RELEASE.version.replace(/-beta$/,'')+' · beta · histórico';$('#releaseHistory').innerHTML=RELEASE.history.map(r=>`<article><strong>${esc(r.version)} · ${esc(r.title)}</strong><small>${esc(r.date)}</small><p>${r.changes.map(esc).join(' ')}</p></article>`).join('');
let polling=false,notified='',availableVersion='';async function checkVersion(){if(document.hidden||polling||!navigator.onLine)return;polling=true;try{const response=await fetch('./version.json?t='+Date.now(),{cache:'no-store',signal:AbortSignal.timeout(8000)});if(!response.ok)return;const latest=await response.json();if(typeof latest.version==='string'&&/^[0-9]+\.[0-9]+\.[0-9]+-beta$/.test(latest.version)&&latest.version!==RELEASE.version){availableVersion=latest.version;if(notified!==latest.version&&!document.querySelector('dialog[open]')){notified=latest.version;$('#updateText').textContent='CATHEU Demo '+latest.version+' está disponível. Atualize para carregar as novidades.';$('#updateDialog').showModal();}}}catch{}finally{polling=false;}}
$('#reloadDemo').onclick=()=>{const next=new URL(location.href);next.searchParams.set('v',availableVersion||RELEASE.version);next.searchParams.set('updated',String(Date.now()));location.replace(next.href);};setInterval(checkVersion,60000);document.addEventListener('visibilitychange',checkVersion);window.addEventListener('online',checkVersion);checkVersion();go(location.hash==='#movimentacoes'?'movimentacoes':'inicio');
